# Generated by Django 4.0 on 2021-12-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='twtter_link',
            new_name='twitter_link',
        ),
    ]
